// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contract.proto

/*
	Package proto is a generated protocol buffer package.

	It is generated from these files:
		contract.proto

	It has these top-level messages:
		Contract
		MethodProto
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Privilege int32

const (
	Privilege_PRIVATE   Privilege = 0
	Privilege_PROTECTED Privilege = 1
	Privilege_PUBLIC    Privilege = 2
)

var Privilege_name = map[int32]string{
	0: "PRIVATE",
	1: "PROTECTED",
	2: "PUBLIC",
}
var Privilege_value = map[string]int32{
	"PRIVATE":   0,
	"PROTECTED": 1,
	"PUBLIC":    2,
}

func (x Privilege) String() string {
	return proto1.EnumName(Privilege_name, int32(x))
}
func (Privilege) EnumDescriptor() ([]byte, []int) { return fileDescriptorContract, []int{0} }

type Contract struct {
	Code string         `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Lang string         `protobuf:"bytes,2,opt,name=Lang,proto3" json:"Lang,omitempty"`
	Apis []*MethodProto `protobuf:"bytes,3,rep,name=apis" json:"apis,omitempty"`
}

func (m *Contract) Reset()                    { *m = Contract{} }
func (m *Contract) String() string            { return proto1.CompactTextString(m) }
func (*Contract) ProtoMessage()               {}
func (*Contract) Descriptor() ([]byte, []int) { return fileDescriptorContract, []int{0} }

func (m *Contract) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Contract) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Contract) GetApis() []*MethodProto {
	if m != nil {
		return m.Apis
	}
	return nil
}

type MethodProto struct {
	Name   string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	InCnt  int32     `protobuf:"varint,2,opt,name=InCnt,proto3" json:"InCnt,omitempty"`
	OutCnt int32     `protobuf:"varint,3,opt,name=OutCnt,proto3" json:"OutCnt,omitempty"`
	Priv   Privilege `protobuf:"varint,4,opt,name=Priv,proto3,enum=proto.Privilege" json:"Priv,omitempty"`
}

func (m *MethodProto) Reset()                    { *m = MethodProto{} }
func (m *MethodProto) String() string            { return proto1.CompactTextString(m) }
func (*MethodProto) ProtoMessage()               {}
func (*MethodProto) Descriptor() ([]byte, []int) { return fileDescriptorContract, []int{1} }

func (m *MethodProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MethodProto) GetInCnt() int32 {
	if m != nil {
		return m.InCnt
	}
	return 0
}

func (m *MethodProto) GetOutCnt() int32 {
	if m != nil {
		return m.OutCnt
	}
	return 0
}

func (m *MethodProto) GetPriv() Privilege {
	if m != nil {
		return m.Priv
	}
	return Privilege_PRIVATE
}

func init() {
	proto1.RegisterType((*Contract)(nil), "proto.Contract")
	proto1.RegisterType((*MethodProto)(nil), "proto.MethodProto")
	proto1.RegisterEnum("proto.Privilege", Privilege_name, Privilege_value)
}
func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Code) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintContract(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if len(m.Lang) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintContract(dAtA, i, uint64(len(m.Lang)))
		i += copy(dAtA[i:], m.Lang)
	}
	if len(m.Apis) > 0 {
		for _, msg := range m.Apis {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintContract(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *MethodProto) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MethodProto) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintContract(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if m.InCnt != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintContract(dAtA, i, uint64(m.InCnt))
	}
	if m.OutCnt != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintContract(dAtA, i, uint64(m.OutCnt))
	}
	if m.Priv != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintContract(dAtA, i, uint64(m.Priv))
	}
	return i, nil
}

func encodeVarintContract(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Contract) Size() (n int) {
	var l int
	_ = l
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Lang)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if len(m.Apis) > 0 {
		for _, e := range m.Apis {
			l = e.Size()
			n += 1 + l + sovContract(uint64(l))
		}
	}
	return n
}

func (m *MethodProto) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.InCnt != 0 {
		n += 1 + sovContract(uint64(m.InCnt))
	}
	if m.OutCnt != 0 {
		n += 1 + sovContract(uint64(m.OutCnt))
	}
	if m.Priv != 0 {
		n += 1 + sovContract(uint64(m.Priv))
	}
	return n
}

func sovContract(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozContract(x uint64) (n int) {
	return sovContract(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lang", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lang = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apis = append(m.Apis, &MethodProto{})
			if err := m.Apis[len(m.Apis)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MethodProto) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MethodProto: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MethodProto: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InCnt", wireType)
			}
			m.InCnt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InCnt |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutCnt", wireType)
			}
			m.OutCnt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OutCnt |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priv", wireType)
			}
			m.Priv = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priv |= (Privilege(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipContract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContract(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContract
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthContract
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowContract
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipContract(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthContract = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContract   = fmt.Errorf("proto: integer overflow")
)

func init() { proto1.RegisterFile("contract.proto", fileDescriptorContract) }

var fileDescriptorContract = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0x2b,
	0x29, 0x4a, 0x4c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x51,
	0x5c, 0x1c, 0xce, 0x50, 0x09, 0x21, 0x21, 0x2e, 0x16, 0xe7, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x24, 0xe6, 0x93, 0x98, 0x97, 0x2e, 0xc1, 0x04, 0x11, 0x03,
	0xb1, 0x85, 0xd4, 0xb8, 0x58, 0x12, 0x0b, 0x32, 0x8b, 0x25, 0x98, 0x15, 0x98, 0x35, 0xb8, 0x8d,
	0x84, 0x20, 0x06, 0xea, 0xf9, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0x04, 0x80, 0xd8, 0x41, 0x60, 0x79,
	0xa5, 0x52, 0x2e, 0x6e, 0x24, 0x41, 0x90, 0x51, 0x7e, 0x89, 0xb9, 0x70, 0xe3, 0x41, 0x6c, 0x21,
	0x11, 0x2e, 0x56, 0xcf, 0x3c, 0xe7, 0xbc, 0x12, 0xb0, 0xf9, 0xac, 0x41, 0x10, 0x8e, 0x90, 0x18,
	0x17, 0x9b, 0x7f, 0x69, 0x09, 0x48, 0x98, 0x19, 0x2c, 0x0c, 0xe5, 0x09, 0xa9, 0x70, 0xb1, 0x04,
	0x14, 0x65, 0x96, 0x49, 0xb0, 0x28, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0x40, 0x2d, 0x06, 0x09, 0x65,
	0xe6, 0xa4, 0xa6, 0xa7, 0x06, 0x81, 0x65, 0xb5, 0x8c, 0xb9, 0x38, 0xe1, 0x42, 0x42, 0xdc, 0x5c,
	0xec, 0x01, 0x41, 0x9e, 0x61, 0x8e, 0x21, 0xae, 0x02, 0x0c, 0x42, 0xbc, 0x5c, 0x9c, 0x01, 0x41,
	0xfe, 0x21, 0xae, 0xce, 0x21, 0xae, 0x2e, 0x02, 0x8c, 0x42, 0x5c, 0x5c, 0x6c, 0x01, 0xa1, 0x4e,
	0x3e, 0x9e, 0xce, 0x02, 0x4c, 0x4e, 0x02, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8,
	0xe0, 0x91, 0x1c, 0xe3, 0x8c, 0xc7, 0x72, 0x0c, 0x49, 0x6c, 0x60, 0xd3, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf4, 0xa8, 0x0a, 0xc4, 0x39, 0x01, 0x00, 0x00,
}
